# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20180129_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='device_identification',
            field=models.CharField(max_length=200),
        ),
    ]
